### ISSUE TITLE
sanitize JOB_NAME

### ISSUE THREAD

**Issue by sue445** [sue445/paraduct#40]
```
variables:
  ruby:
    - 1.9.3-p545
    - 2.0.0-p451
  gemfile:
    - gemfiles/rails3_2.gemfile
    - gemfiles/rails4_0.gemfile
```

now:  RUBY_1.9.3-p545_GEMFILE_gemfiles/rails3_2.gemfile
new: RUBY_1.9.3-p545_GEMFILE_gemfiles_rails3_2.gemfile
