### ISSUE TITLE
relax exclude definition

### ISSUE THREAD

**Issue by sue445** [sue445/paraduct#72]
``` yaml
variables:
  ruby:
    - 2.0.0-p451
    - 2.1.4
  gemfile:
    - rails4_0.gemfile
    - rails4_1.gemfile
```

When I want to exclude all `2.0.0-p451`
## Now

``` yaml
exclude:
  - ruby: 2.0.0-p451
    gemfile: rails4_0.gemfile
  - ruby: 2.0.0-p451
    gemfile: rails4_1.gemfile
```
## Future

``` yaml
exclude:
  - ruby: 2.0.0-p451
```
